version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysqldocker
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - /home/gabriel/dockerdata/mysql:/var/lib/mysql


  jms:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  eureka:
    image: ggab78/mssc-brewery-eureka
    ports:
      - 8761:8761

  config:
    image: ggab78/mssc-config-server
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/

  inventory-service:
    image: ggab78/mssc-beer-inventory-service
    ports:
      - 8082:8082
    depends_on:
      - eureka
      - config
      - jms
      - mysql
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      SPRING_PROFILES_ACTIVE: local-discovery, docker
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://MyUserName:MySecretPassword@config:8888"}}}}'
